#!/usr/bin/env python3
"""
Deterministic seed generator for medical mini-app demo data.

Usage:
  python seed/generate_data.py
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
import random
from pathlib import Path


RNG = random.Random(20260407)


def q(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


@dataclass(frozen=True)
class PersonName:
    first: str
    last: str

    @property
    def full(self) -> str:
        return f"{self.first} {self.last}"


FIXTURE_BY_SCENARIO: dict[str, list[PersonName]] = {
    "M1_ALLOW": [
        PersonName("Jordan", "Hayes"),
        PersonName("Morgan", "Reed"),
        PersonName("Taylor", "Brooks"),
    ],
    "M2_ALLERGY_DENY": [
        PersonName("Riley", "Chen"),
        PersonName("Alex", "Rivera"),
        PersonName("Casey", "Nguyen"),
    ],
    "M3_TRIAL_DENY": [
        PersonName("Sam", "Okonkwo"),
        PersonName("Jamie", "Foster"),
        PersonName("Drew", "Patel"),
    ],
    "M4_SEVERE_AE": [
        PersonName("Avery", "Morrison"),
        PersonName("Blake", "Okada"),
        PersonName("Dakota", "Flynn"),
    ],
    "M5_REVIEW_PENDING": [
        PersonName("Nico", "Harper"),
        PersonName("Remy", "Santos"),
        PersonName("Sage", "Lombardi"),
    ],
    "M6_REPORTER_MISMATCH": [
        PersonName("Lake", "Kim"),
        PersonName("Rowan", "Gupta"),
        PersonName("Skyler", "Adams"),
    ],
}


EXTRA_FIRST = [
    "Aidan", "Bianca", "Carson", "Delia", "Elliot", "Fatima", "Gavin", "Hana",
    "Isaac", "Janelle", "Keiran", "Leila", "Marta", "Noah", "Olivia", "Pavel",
    "Quinn", "Rafael", "Selena", "Tristan", "Uma", "Victor", "Willa", "Xavier",
    "Yara", "Zane", "Adriana", "Brett", "Celine", "Diego", "Elena", "Farah",
    "Greta", "Hector", "Ines", "Jonah", "Kira", "Luca", "Mina", "Nolan",
]

EXTRA_LAST = [
    "Abbott", "Bishop", "Carter", "Dalton", "Espinoza", "Farrell", "Gibson", "Hughes",
    "Iverson", "Jenkins", "Keller", "Larson", "Mendez", "Nash", "Ortega", "Phelps",
    "Quintero", "Ramos", "Shah", "Turner", "Usman", "Valdez", "West", "Xu",
    "Young", "Zimmerman", "Allen", "Bennett", "Coleman", "Diaz", "Edwards", "Fletcher",
]


def build_patients(total: int = 96) -> list[PersonName]:
    names: list[PersonName] = []
    used: set[str] = set()

    for cohort in FIXTURE_BY_SCENARIO.values():
        for name in cohort:
            names.append(name)
            used.add(name.full.lower())

    while len(names) < total:
        n = PersonName(RNG.choice(EXTRA_FIRST), RNG.choice(EXTRA_LAST))
        if n.full.lower() in used:
            continue
        names.append(n)
        used.add(n.full.lower())

    return names


def main() -> None:
    out = Path(__file__).with_name("data.sql")
    sql: list[str] = []
    append = sql.append

    append("-- Generated by seed/generate_data.py")
    append("-- Deterministic synthetic seed data for medical mini-app")
    append("BEGIN;")
    append("")
    append("TRUNCATE TABLE")
    append("  adverse_events,")
    append("  trial_enrollment_reviews,")
    append("  trial_allowed_medications,")
    append("  trial_enrollment_medications,")
    append("  trial_enrollment_prescribers,")
    append("  trial_enrollments,")
    append("  prescriptions,")
    append("  medication_contraindications,")
    append("  patient_allergies,")
    append("  patient_conditions,")
    append("  adverse_event_types,")
    append("  medication_ingredients,")
    append("  ingredients,")
    append("  medications,")
    append("  drug_classes,")
    append("  trials,")
    append("  doctors,")
    append("  patients,")
    append("  hospitals")
    append("RESTART IDENTITY CASCADE;")
    append("")

    hospitals = [
        ("HOSP-001", "Northgate Medical Center"),
        ("HOSP-002", "Riverside University Hospital"),
        ("HOSP-003", "Harbor Point Clinic"),
        ("HOSP-004", "Cedar Grove Health"),
        ("HOSP-005", "Summit Valley Hospital"),
        ("HOSP-006", "Southview Care Network"),
        ("HOSP-007", "Lakeside Specialty Center"),
        ("HOSP-008", "Cityline Community Hospital"),
        ("HOSP-009", "Maple Ridge Medical"),
        ("HOSP-010", "Westbrook Clinical Institute"),
        ("HOSP-011", "Pinecrest General"),
        ("HOSP-012", "Eastgate Research Hospital"),
    ]
    for idx, (biz_id, name) in enumerate(hospitals, start=1):
        append(
            "INSERT INTO hospitals (id, hospital_id, name, city, state, postal_code) VALUES "
            f"({idx}, {q(biz_id)}, {q(name)}, {q('Metro City')}, {q('CA')}, {q(f'94{idx:03d}')});"
        )
    append("")

    patients = build_patients(96)
    patient_id_by_name: dict[str, int] = {}
    for idx, p in enumerate(patients, start=1):
        dob = date(1948, 1, 1) + timedelta(days=RNG.randint(0, 25000))
        patient_code = f"PAT-{idx:04d}"
        patient_id_by_name[p.full] = idx
        append(
            "INSERT INTO patients (id, patient_id, first_name, last_name, date_of_birth, sex_at_birth) VALUES "
            f"({idx}, {q(patient_code)}, {q(p.first)}, {q(p.last)}, {q(dob.isoformat())}, {q(RNG.choice(['F','M']))});"
        )
    append("")

    doctor_first = ["Priya", "Elijah", "Naomi", "Oliver", "Mei", "Hugo", "Sonia", "Caleb", "Lina", "Mateo"]
    doctor_last = ["Watson", "Ibrahim", "Khan", "Mitchell", "Park", "Singh", "Lopez", "Norris", "Bauer", "Reyes"]
    roles = (["physician"] * 16) + (["investigator"] * 8) + (["pharmacist"] * 8)
    RNG.shuffle(roles)
    for idx in range(1, 33):
        role = roles[idx - 1]
        append(
            "INSERT INTO doctors (id, license_id, first_name, last_name, role, specialty) VALUES "
            f"({idx}, {q(f'DOC-{idx:04d}')}, {q(RNG.choice(doctor_first))}, {q(RNG.choice(doctor_last))}, "
            f"{q(role)}, {q(RNG.choice(['oncology','cardiology','internal medicine','family medicine','clinical pharmacology']))});"
        )
    append("")

    trials = [
        ("TRIAL-001", "Beta-Lactam Safety in Adults"),
        ("TRIAL-002", "Targeted Therapy Cohort A"),
        ("TRIAL-003", "Immunotherapy Combination Study"),
        ("TRIAL-004", "Pediatric Dosing Validation"),
        ("TRIAL-005", "Cardio-Metabolic Drug Interaction Trial"),
        ("TRIAL-006", "Outpatient Adherence Optimization"),
    ]
    for idx, (trial_id, title) in enumerate(trials, start=1):
        append(
            "INSERT INTO trials (id, trial_id, title, phase, status, starts_on, ends_on) VALUES "
            f"({idx}, {q(trial_id)}, {q(title)}, {q(RNG.choice(['I','II','III']))}, {q('active')}, "
            f"{q('2025-01-01')}, {q('2027-12-31')});"
        )
    append("")

    classes = [
        ("BETA_LACTAM", "Beta Lactam"),
        ("ACE_INHIBITOR", "ACE Inhibitor"),
        ("BETA_BLOCKER", "Beta Blocker"),
        ("STATIN", "Statin"),
        ("INSULIN", "Insulin"),
        ("ANTIEMETIC", "Antiemetic"),
        ("IMMUNOTHERAPY", "Immunotherapy"),
        ("CORTICOSTEROID", "Corticosteroid"),
    ]
    for idx, (code, name) in enumerate(classes, start=1):
        append(
            f"INSERT INTO drug_classes (id, class_code, name) VALUES ({idx}, {q(code)}, {q(name)});"
        )
    append("")

    ingredients = [("ING-PEN", "Penicillin"), ("ING-AMOX", "Amoxicillin"), ("ING-CLAV", "Clavulanate")]
    for i in range(4, 43):
        ingredients.append((f"ING-{i:03d}", f"Ingredient {i:03d}"))
    for idx, (code, name) in enumerate(ingredients, start=1):
        append(
            f"INSERT INTO ingredients (id, ingredient_code, name) VALUES ({idx}, {q(code)}, {q(name)});"
        )
    append("")

    for idx in range(1, 85):
        class_id = ((idx - 1) % len(classes)) + 1
        is_penicillin = idx in (1, 2, 3, 11, 19)
        code = f"MED-{idx:03d}"
        med_name = f"Medication {idx:03d}"
        if is_penicillin:
            med_name = f"Penicillin Family {idx:03d}"
            class_id = 1
        append(
            "INSERT INTO medications (id, drug_code, name, drug_class_id, warning_text, pediatric_warning, "
            "is_controlled_substance, trial_restricted) VALUES "
            f"({idx}, {q(code)}, {q(med_name)}, {class_id}, {q('Monitor for interactions')}, "
            f"{q(idx % 7 == 0)}, {q(idx % 13 == 0)}, {q(idx % 5 == 0)});"
        )
    append("")

    link_count = 0
    for med_id in range(1, 85):
        if med_id in (1, 2, 3, 11, 19):
            ingredient_ids = [1, 2]
        else:
            picks = RNG.sample(range(4, 43), RNG.randint(1, 3))
            ingredient_ids = list(set(picks))
        for ing_id in ingredient_ids:
            link_count += 1
            append(
                f"INSERT INTO medication_ingredients (medication_id, ingredient_id) VALUES ({med_id}, {ing_id});"
            )
    append(f"-- medication_ingredients rows: {link_count}")
    append("")

    ae_types = [
        ("AE-N", "Nausea"),
        ("AE-R", "Rash"),
        ("AE-H", "Headache"),
        ("AE-F", "Fatigue"),
        ("AE-L", "Liver enzyme elevation"),
        ("AE-C", "Cardiac event"),
        ("AE-D", "Dizziness"),
        ("AE-P", "Pain"),
    ]
    for code, desc in ae_types:
        append(f"INSERT INTO adverse_event_types (code, description) VALUES ({q(code)}, {q(desc)});")
    append("")

    cond_codes = ["HTN", "DM2", "ASTHMA", "CKD", "HF", "CANCER", "ANXIETY", "HYPERLIPID"]
    condition_rows = 0
    for patient_id in range(1, 97):
        selected_codes = RNG.sample(cond_codes, RNG.randint(1, 3))
        for cc in selected_codes:
            condition_rows += 1
            append(
                "INSERT INTO patient_conditions (patient_id, condition_code, condition_name, is_active, diagnosed_on) VALUES "
                f"({patient_id}, {q(cc)}, {q(cc.title())}, {q(RNG.random() > 0.15)}, {q('2023-01-01')});"
            )
    append(f"-- patient_conditions rows: {condition_rows}")
    append("")

    # M2 explicit verified allergy conflicts
    m2_names = [p.full for p in FIXTURE_BY_SCENARIO["M2_ALLERGY_DENY"]]
    for full_name in m2_names:
        pid = patient_id_by_name[full_name]
        append(
            "INSERT INTO patient_allergies (patient_id, allergy_target_type, ingredient_id, reaction, severity, verified, noted_on) VALUES "
            f"({pid}, 'ingredient', 1, {q('anaphylaxis')}, {q('high')}, TRUE, {q('2024-06-01')});"
        )

    allergy_rows = 3
    while allergy_rows < 230:
        pid = RNG.randint(1, 96)
        target = "ingredient" if RNG.random() < 0.8 else "medication"
        verified = RNG.random() < 0.7
        if target == "ingredient":
            ing_id = RNG.randint(1, 42)
            append(
                "INSERT INTO patient_allergies (patient_id, allergy_target_type, ingredient_id, reaction, severity, verified, noted_on) VALUES "
                f"({pid}, 'ingredient', {ing_id}, {q(RNG.choice(['rash','hives','nausea','anaphylaxis']))}, "
                f"{q(RNG.choice(['low','moderate','high']))}, {q(verified)}, {q('2024-05-01')});"
            )
        else:
            med_id = RNG.randint(1, 84)
            append(
                "INSERT INTO patient_allergies (patient_id, allergy_target_type, medication_id, reaction, severity, verified, noted_on) VALUES "
                f"({pid}, 'medication', {med_id}, {q(RNG.choice(['rash','hives','nausea']))}, "
                f"{q(RNG.choice(['low','moderate']))}, {q(verified)}, {q('2024-05-01')});"
            )
        allergy_rows += 1
    append(f"-- patient_allergies rows: {allergy_rows}")
    append("")

    for _ in range(70):
        med_id = RNG.randint(1, 84)
        cc = RNG.choice(cond_codes)
        min_age = RNG.choice([None, 12, 18, 65])
        max_age = RNG.choice([None, 16, 75, 90])
        append(
            "INSERT INTO medication_contraindications (medication_id, condition_code, min_age_years, max_age_years, contraindication_level, notes) VALUES "
            f"({med_id}, {q(cc)}, {q(min_age)}, {q(max_age)}, {q(RNG.choice(['absolute','relative']))}, "
            f"{q('Policy driven contraindication')});"
        )
    append("")

    # trial_allowed_medications: 12 meds per trial
    allowed_map: dict[int, set[int]] = {}
    for trial_id in range(1, 7):
        allowed = set(RNG.sample(range(1, 85), 12))
        allowed_map[trial_id] = allowed
        for med_id in sorted(allowed):
            append(
                f"INSERT INTO trial_allowed_medications (trial_id, medication_id) VALUES ({trial_id}, {med_id});"
            )
    append("")

    # Enrollments
    enrollment_rows = 0
    enrollment_pk = 1
    enrollment_for_patient: dict[int, int] = {}

    # Seed key scenario patients first
    key_patient_names = (
        [p.full for p in FIXTURE_BY_SCENARIO["M3_TRIAL_DENY"]]
        + [p.full for p in FIXTURE_BY_SCENARIO["M5_REVIEW_PENDING"]]
        + [p.full for p in FIXTURE_BY_SCENARIO["M6_REPORTER_MISMATCH"]]
    )
    for full_name in key_patient_names:
        pid = patient_id_by_name[full_name]
        trial_id = RNG.randint(1, 6)
        site_id = RNG.randint(1, 12)
        append(
            "INSERT INTO trial_enrollments (id, enrollment_id, patient_id, trial_id, site_id, enrolled_at, status) VALUES "
            f"({enrollment_pk}, {q(f'ENR-{enrollment_pk:04d}')}, {pid}, {trial_id}, {site_id}, "
            f"{q('2025-01-15 10:00:00+00')}, {q('active')});"
        )
        enrollment_for_patient[pid] = enrollment_pk
        enrollment_rows += 1
        enrollment_pk += 1

    while enrollment_rows < 58:
        pid = RNG.randint(1, 96)
        if pid in enrollment_for_patient:
            continue
        trial_id = RNG.randint(1, 6)
        site_id = RNG.randint(1, 12)
        status = RNG.choice(["active", "active", "screening", "paused", "completed"])
        append(
            "INSERT INTO trial_enrollments (id, enrollment_id, patient_id, trial_id, site_id, enrolled_at, status) VALUES "
            f"({enrollment_pk}, {q(f'ENR-{enrollment_pk:04d}')}, {pid}, {trial_id}, {site_id}, "
            f"{q('2025-02-01 09:00:00+00')}, {q(status)});"
        )
        enrollment_for_patient[pid] = enrollment_pk
        enrollment_rows += 1
        enrollment_pk += 1
    append("")

    # enrollment prescribers and enrollment medications
    enrollment_prescriber_map: dict[int, set[str]] = {}
    for enr_id in range(1, enrollment_pk):
        prescriber_count = RNG.randint(1, 3)
        licenses = set()
        while len(licenses) < prescriber_count:
            licenses.add(f"DOC-{RNG.randint(1, 32):04d}")
        enrollment_prescriber_map[enr_id] = licenses
        for lic in sorted(licenses):
            append(
                f"INSERT INTO trial_enrollment_prescribers (enrollment_id, doctor_license) VALUES ({enr_id}, {q(lic)});"
            )

        trial_id = ((enr_id - 1) % 6) + 1
        meds = RNG.sample(sorted(allowed_map[trial_id]), RNG.randint(1, 3))
        for med_id in meds:
            append(
                f"INSERT INTO trial_enrollment_medications (enrollment_id, medication_id) VALUES ({enr_id}, {med_id});"
            )
    append("")

    # M5 pending reviews
    for full_name in [p.full for p in FIXTURE_BY_SCENARIO["M5_REVIEW_PENDING"]]:
        pid = patient_id_by_name[full_name]
        enr_id = enrollment_for_patient[pid]
        append(
            "INSERT INTO trial_enrollment_reviews (enrollment_id, reviewer_license, approval_status, reviewed_at, review_notes) VALUES "
            f"({enr_id}, {q('DOC-0002')}, 'pending', NULL, {q('Awaiting committee approval')});"
        )
    for _ in range(34):
        enr_id = RNG.randint(1, enrollment_pk - 1)
        status = RNG.choice(["approved", "approved", "rejected", "pending"])
        reviewed_at = None if status == "pending" else "2025-03-03 12:00:00+00"
        append(
            "INSERT INTO trial_enrollment_reviews (enrollment_id, reviewer_license, approval_status, reviewed_at, review_notes) VALUES "
            f"({enr_id}, {q(f'DOC-{RNG.randint(1, 32):04d}')}, {q(status)}, {q(reviewed_at)}, {q('Generated review row')});"
        )
    append("")

    # Prescriptions
    rx_rows = 0
    for idx in range(1, 301):
        pid = RNG.randint(1, 96)
        med_id = RNG.randint(1, 84)
        # Keep M1 cohort away from penicillin allergy conflict patterns.
        if patients[pid - 1].full in [p.full for p in FIXTURE_BY_SCENARIO["M1_ALLOW"]] and med_id in (1, 2, 3, 11, 19):
            med_id = 44
        append(
            "INSERT INTO prescriptions (rx_id, patient_id, prescriber_license, hospital_id, medication_id, dose, frequency, route, "
            "starts_on, ends_on, status, is_trial_related) VALUES "
            f"({q(f'RX-{idx:05d}')}, {pid}, {q(f'DOC-{RNG.randint(1, 32):04d}')}, {RNG.randint(1,12)}, {med_id}, "
            f"{q(RNG.choice(['5mg','10mg','20mg','250mg']))}, {q(RNG.choice(['daily','bid','tid']))}, {q('oral')}, "
            f"{q('2025-02-15')}, {q('2025-05-15')}, {q(RNG.choice(['active','active','paused','stopped']))}, {q(RNG.random() < 0.25)});"
        )
        rx_rows += 1
    append(f"-- prescriptions rows: {rx_rows}")
    append("")

    # Adverse events with explicit M4 and M6 coverage
    ae_rows = 0
    m4_names = [p.full for p in FIXTURE_BY_SCENARIO["M4_SEVERE_AE"]]
    for i, full_name in enumerate(m4_names, start=1):
        pid = patient_id_by_name[full_name]
        append(
            "INSERT INTO adverse_events (adverse_event_id, patient_id, event_type_code, reporting_physician_license, "
            "enrollment_id, severity, status, details, reported_at) VALUES "
            f"({q(f'AE-M4-{i:03d}')}, {pid}, {q('AE-C')}, {q('DOC-0003')}, NULL, 4, 'open', "
            f"{q('Open severe AE for M4 cohort')}, {q('2025-03-02 08:00:00+00')});"
        )
        ae_rows += 1

    m6_names = [p.full for p in FIXTURE_BY_SCENARIO["M6_REPORTER_MISMATCH"]]
    for i, full_name in enumerate(m6_names, start=1):
        pid = patient_id_by_name[full_name]
        enr_id = enrollment_for_patient[pid]
        allowed_reporters = enrollment_prescriber_map[enr_id]
        mismatch = next(lic for lic in [f"DOC-{n:04d}" for n in range(1, 33)] if lic not in allowed_reporters)
        append(
            "INSERT INTO adverse_events (adverse_event_id, patient_id, event_type_code, reporting_physician_license, "
            "enrollment_id, severity, status, details, reported_at) VALUES "
            f"({q(f'AE-M6-{i:03d}')}, {pid}, {q('AE-R')}, {q(mismatch)}, {enr_id}, 3, 'open', "
            f"{q('Reporter is intentionally outside enrollment prescriber set')}, {q('2025-03-04 08:00:00+00')});"
        )
        ae_rows += 1

    while ae_rows < 52:
        pid = RNG.randint(1, 96)
        full_name = patients[pid - 1].full
        if full_name in [p.full for p in FIXTURE_BY_SCENARIO["M1_ALLOW"]] and RNG.random() < 0.6:
            severity = RNG.choice([1, 2])
            status = "resolved"
        else:
            severity = RNG.randint(1, 5)
            status = RNG.choice(["open", "resolved", "closed"])
        enr_id = enrollment_for_patient.get(pid)
        append(
            "INSERT INTO adverse_events (adverse_event_id, patient_id, event_type_code, reporting_physician_license, "
            "enrollment_id, severity, status, details, reported_at) VALUES "
            f"({q(f'AE-{ae_rows + 1:04d}')}, {pid}, {q(RNG.choice(['AE-N','AE-R','AE-H','AE-F','AE-L','AE-D','AE-P']))}, "
            f"{q(f'DOC-{RNG.randint(1, 32):04d}')}, {q(enr_id)}, {severity}, {q(status)}, {q('Generated adverse event')}, "
            f"{q('2025-03-10 09:00:00+00')});"
        )
        ae_rows += 1
    append(f"-- adverse_events rows: {ae_rows}")
    append("")

    append("-- Align sequences after explicit id inserts")
    append("SELECT setval('hospitals_id_seq', (SELECT COALESCE(MAX(id), 1) FROM hospitals), true);")
    append("SELECT setval('patients_id_seq', (SELECT COALESCE(MAX(id), 1) FROM patients), true);")
    append("SELECT setval('doctors_id_seq', (SELECT COALESCE(MAX(id), 1) FROM doctors), true);")
    append("SELECT setval('trials_id_seq', (SELECT COALESCE(MAX(id), 1) FROM trials), true);")
    append("SELECT setval('drug_classes_id_seq', (SELECT COALESCE(MAX(id), 1) FROM drug_classes), true);")
    append("SELECT setval('medications_id_seq', (SELECT COALESCE(MAX(id), 1) FROM medications), true);")
    append("SELECT setval('ingredients_id_seq', (SELECT COALESCE(MAX(id), 1) FROM ingredients), true);")
    append("SELECT setval('trial_enrollments_id_seq', (SELECT COALESCE(MAX(id), 1) FROM trial_enrollments), true);")
    append("COMMIT;")
    append("")
    append("-- Cohort quick checks")
    append("-- M1_ALLOW: Jordan Hayes, Morgan Reed, Taylor Brooks")
    append("-- M2_ALLERGY_DENY: Riley Chen, Alex Rivera, Casey Nguyen")
    append("-- M3_TRIAL_DENY: Sam Okonkwo, Jamie Foster, Drew Patel")
    append("-- M4_SEVERE_AE: Avery Morrison, Blake Okada, Dakota Flynn")
    append("-- M5_REVIEW_PENDING: Nico Harper, Remy Santos, Sage Lombardi")
    append("-- M6_REPORTER_MISMATCH: Lake Kim, Rowan Gupta, Skyler Adams")

    out.write_text("\n".join(sql), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
